name: Studio Unit Tests

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]
    steps:
      - uses: actions/checkout@v1
      - name: Caching dependencies
        id: cache-deps
        uses: actions/cache@v1
        with:
          path: node_modules
          key: v1-deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            v1-deps-${{ hashFiles('yarn.lock') }}
            v1-deps-
      - name: Installing dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn 
      - name: Linting
        run: yarn lint
      - name: Setting up pre-test task
        # this will prevent potential connection failure in the next task
        run: yarn pretest
      - name: Testing with coverage
        run: yarn test
      - name: Uploading to Codecov
        run: bash <(curl -s https://codecov.io/bash -t $CODECOV_TOKEN)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
      